//@File(label = "Input image directory", style = "directory") inputImageDir
//@ File (label="Input label image directory",style="directory") inputLabelDir
//@String (label = "Image file suffix", value = ".tif") imageSuffix
//@ String (label = "Label image suffix",value = "_cp_masks.png") labelSuffix
//@File(label = "Output snapshot folder:", style = "directory") outputImageDir
//@File(label = "Output ROI folder:", style = "directory") outputRoiDir
//@Integer(label = "Minimum area for objects (scaled units):", value = 10) minSize

// crop_from_label_image_batch.ijm
// ImageJ/Fiji macro by Theresa Swayne, Columbia University, 2025-26
// Process a batch of images and corresponding ROIsets to generate one image for each ROI, with the area outside cleared
// optional adjustment of ROIs based on edge position and size

//  -------- Suggested text for acknowledgement -----------
//   "These studies used the Confocal and Specialized Microscopy Shared Resource 
//   of the Herbert Irving Comprehensive Cancer Center at Columbia University, 
//   funded in part through the NIH/NCI Cancer Center Support Grant P30CA013696."

// Input: A folder of images (can be hyperstacks), and a folder of corresponding label images (e.g. generated by cellpose)
//
// Output: A cropped stack (or single plane) corresponding to each ROI, 
//		plus a snapshot of the ROI locations.
//		Non-rectangular ROIs are cropped to their bounding box and the area outside the ROI is cleared to black.
//		The ROI sets are also saved, using the same base name as the image.
// Special feature: fixes colors that are messed up by exporting Volocity OME TIFFs
// Usage: Run the macro and select input and output locations. 
//   The label image is expected to have the same name as the masks (minus extension) followed by the suffix provided.

// TO USE: Place all input images in the input image folder. 
//			Label images can be in the same or a different folder (but not nested in the image folder!). 
// 	Create a folder for the output files. 
//  Run the script in Fiji. 

// ---- Setup ----

while (nImages>0) { // clean up open images
	selectImage(nImages);
	close();
}
IJ.log("\\Clear"); // clear Log window
roiManager("reset");
run("Bio-Formats Macro Extensions"); // supports native microscope files

// keep track of time
startTime = getTime();

setBatchMode(true); // faster performance but may not work for all functions


// ---- Run ----

print("Starting");

// Call the processFolder function, including the parameters collected at the beginning of the script
// collect number of files processed

filenum = processFolder(inputImageDir, inputLabelDir, imageSuffix, labelSuffix, outputImageDir, outputRoiDir, minSize);

// Clean up images and get out of batch mode

while (nImages > 0) { // clean up open images
	selectImage(nImages);
	close(); 
}
setBatchMode(false);

time = getTime();
elapsedTime = (time - startTime)/1000;
print("Processed",filenum,"images in", elapsedTime , "sec");

// save log
selectWindow("Log");
saveAs("text", outputRoiDir + File.separator + "Crop_Log.txt");


// ---- Functions ----

function processFolder(inputImageDir, inputLabelDir, imageSuffix, labelSuffix, outputImageDir, outputRoiDir, minSize) {

	// this function searches for files matching the criteria and sends them to the processFile function
	filenum = 0;
	print("Processing folder", inputImageDir);
	// scan folder tree to find files with correct suffix
	list = getFileList(inputImageDir);
	list = Array.sort(list);
	for (i = 0; i < list.length; i++) {
		// do not handle nested folders as this is not likely to occur with single label directory
		//if(File.isDirectory(input + File.separator + list[i])) {
			//processFolder(input + File.separator + list[i], inputLabelDir, fileSuffix, labelSuffix, imagePath, roiPath); // handles nested folders
		//}
		if(endsWith(list[i], imageSuffix)) {
			filenum = filenum + 1;
			processFile(inputImageDir, inputLabelDir, imageSuffix, labelSuffix, outputImageDir, outputRoiDir, list[i], filenum, minSize); // passes the filename and parameters to the processFile function
		}
	}
	return filenum;
} // end of processFolder function


function processFile(inputImageDir, inputLabelDir, imageSuffix, labelSuffix, outputImageDir, outputRoiDir, fileName, fileNumber, minSize) {
	
	// this function processes a single image
	
	// ---------- SETUP
	
	imagePath = inputImageDir + File.separator + fileName;
	
	// open the image file
	run("Bio-Formats", "open=&imagePath");
	id = getImageID();
	rename("image");
	getPixelSize(scaleUnit, pixelWidth, pixelHeight);
	print("Pixel size in the image is",pixelWidth);
			 
	// determine the name of the file without extension -- support ome tiff
    if(endsWith(fileName, ".ome.tiff")){
	    basename_temp = File.getNameWithoutExtension(fileName);
	    basename = File.getNameWithoutExtension(basename_temp);
	    extension = ".ome.tiff";
    }
    else{
		dotIndex = lastIndexOf(fileName, ".");
	    basename = File.getNameWithoutExtension(fileName);
		extension = substring(fileName, dotIndex);
    }
	
	print("Processing image",fileNumber," at path" ,imagePath, "with basename",basename, "and extension",extension );	
	
	// open the corresponding label image
	labelPath = inputLabelDir + File.separator + basename + labelSuffix;
	print("Opening label image at", labelPath);
	if (File.exists(labelPath)) {
		open(labelPath);
		rename("label");
	}
	else {
		print("No matching label image at " , labelPath);
		return; // skip to next image in the list
	}
	
	// remove border labels 
	// (note this may still leave some cells on edges, 
	//  due to some images having partial black borders before segmentation)
	selectImage("label");
	print("Removing labels touching the edges");
	run("Remove Border Labels", "left right top bottom");
	selectImage("label");
	close();
	selectImage("label-killBorders");
	rename("label");
	
	// filtering by area
	minSizePixels = minSize/(pixelWidth*pixelWidth);
	print("Removing ROIs smaller than", minSize, "scaled units (",minSizePixels,"pixels)");
	selectImage("label");
	run("Label Size Filtering", "operation=Greater_Than size=&minSizePixels");
	selectImage("label");
	close();
	selectImage("label-sizeFilt");
	rename("label");

	// generate ROIs from the labels
	roiManager("reset");
	numROIs = roiManager("count");
	//print("Before loading the labels, there are",numROIs, "ROIs");
	selectImage("label");
	
	// name the ROIs as "roi_" plus 2 digits
	run("Label Map to ROIs", "connectivity=C4 vertex_location=Corners name_pattern=roi_%02d"); 
	
	numROIs = roiManager("count");
	print("After editing the labels, there are",numROIs, "ROIs");
	
	// ---------- DOCUMENT ROI LOCATIONS

	// determine image / stack dimensions
	selectWindow("image");
	getDimensions(width, height, channels, slices, frames);
	
	// view as composite using the 1st timepoint, middle slice
	if (frames > 1) {
		Stack.setFrame(1);
	}
	if (slices > 1) {
		midslice = Math.ceil(slices/2);
		Stack.setSlice(midslice);
	}
	if (channels > 1) {
		// auto contrast all channels and fix colors specific to Cue5 images
		Stack.setDisplayMode("color");
		for (i = 1; i <= channels; i ++) {
			Stack.setChannel(i);
			resetMinAndMax;
			if(i == 3) {
				run("Grays");
			}
			if (i == 4) {
				run("Red");
			}
			if (i == 5) {
				run("Green");
			}
		}
		if (is("composite")) {
			Stack.setDisplayMode("composite"); // this command raises error if image is not composite
		}
	}
	else { 
		// auto contrast a single channel 
		resetMinAndMax;
	}
	
	// create an RGB snapshot
	
	selectWindow("image");
	run("Select None");

	if (is("composite")) {
		Stack.setDisplayMode("composite"); // this command raises error if image is not composite
		run("Stack to RGB", "keep"); // create an RGB image while keeping the original
	}
	else {

	//	run("Duplicate...", "title=copy duplicate"); // for single-channel non-RGB images; Flatten doesn't create new window
		run("Duplicate...", "title=copy"); // for single-channel non-RGB images; Flatten doesn't create new window
	}
	rgbID = getImageID(); // current image, should be the RGB or the duplicate
	selectImage(rgbID);
	
	// display ROIs on the image
	run("Labels...", "color=white font=16 show draw bold"); // increase label size above the default
	roiManager("Show All with labels");
	run("Flatten"); // now we should have a new RGB with flattened overlay
	flatID = getImageID();
	selectImage(flatID);
	saveAs("tiff", outputImageDir+File.separator+basename+"_ROIlocs.tif");
	
	print("Saved snapshot for image",basename);
	
	// close images from snapshot generation
	if (isOpen(flatID)) {
		selectImage(flatID);
		close();
	}
	if (isOpen(rgbID)) {
		selectImage(rgbID);
		close();
	}
	
	// ---------- CROP AND SAVE
	
	// make sure nothing is selected to begin with
	selectImage(id);
	roiManager("deselect");
	run("Select None");
	
	numROIs = roiManager("count");	
	
	if (numROIs == 0) {
		print("No ROIs to process");
		while (nImages > 0) { // clean up open images
			selectImage(nImages);
			close(); 
		}
		run("Collect Garbage");
		return; // go to next image
	}
		
	// how much to pad?
	digits = Math.ceil((log(numROIs + 1)/log(10)));
	
	for(roiIndex=0; roiIndex < numROIs; roiIndex++) { // loop through ROIs 
		selectImage(id);
		roiNum = roiIndex + 1; // so that image names start with 1 like the ROI labels
		roiManager("select", roiIndex);  // ROI indices start with 0
		roiName = Roi.getName();
		print("The original name of ROI number",roiNum, "is",roiName);
		roiNumPad = IJ.pad(roiNum, digits);
		roiManager("rename", roiNumPad);
		cropName = basename+"_roi_"+roiNumPad + ".tif";
		run("Duplicate...", "title=&cropName duplicate"); // creates the cropped stack
		
		// clear areas outside the cell ROI
		selectWindow(cropName);
		if ((selectionType() != 0) && (selectionType() != -1)) {
			run("Clear Outside","stack"); // this works because non-rectangular rois are still active on the cropped image
			run("Select None");// clears the selection that is otherwise saved with the image (although it can be recovered with "restore selection")
		}
		saveAs("tiff", outputImageDir+File.separator+cropName);
		print("Saving ROI",roiNum,"as",cropName);
		selectWindow(cropName);
		close();
	}
		
	// save the ROI set renamed in sequence
	roiFile = basename + "_ROIs.zip"; 
	roiPath = outputRoiDir + File.separator +roiFile;
	roiManager("deselect"); // ensure all ROIs are saved
	roiManager("save", roiPath);
	
	// ---------- CLEANUP
	
	run("Select None");
	print("Processed",numROIs," ROIs.");
	selectImage(id);
	close();
	roiManager("Reset");

	// extra cleanup step
	while (nImages > 0) { // clean up open images
		selectImage(nImages);
		close(); 
	}
	run("Collect Garbage");
	
} // end of processFile function


	