//@ File (label="Input image",style="file") inputImage
//@ File (label="Input label image directory",style="directory") inputLabelDir
//@ String (label = "Label image suffix",value = "_cp_masks.png") suffix
//@File(label = "Output snapshot folder:", style = "directory") imagePath
//@File(label = "Output ROI folder:", style = "directory") roiPath
//
// curate_rois_from_label.ijm
// ImageJ/Fiji macro by Theresa Swayne, Columbia University, 2026

// -------- Suggested text for acknowledgement -----------
//   "These studies used the Confocal and Specialized Microscopy Shared Resource 
//   of the Herbert Irving Comprehensive Cancer Center at Columbia University, 
//   funded in part through the NIH/NCI Cancer Center Support Grant P30CA013696."

// Input: An image or hyperstack, a corresponding label image (e.g. generated by cellpose)
//
// Output: A cropped stack (or single plane) corresponding to each ROI, 
//		plus a snapshot of the ROI locations.
//		Non-rectangular ROIs are cropped to their bounding box and the area outside the ROI is cleared to black.
//		The ROIs are also saved with their numbers, using the same base name as the image.
//	Output images are numbered from 0 to the number of ROIs, 
//		and are saved in a folder of the user's choice.
// Special feature: fixes colors that are messed up by exporting Volocity OME TIFFs
// Usage: Run the macro and select input and output locations. 
//   The label image is expected to have the same name as the masks (minus extension) followed by the suffix provided.


// ---- Setup ----

while (nImages>0) { // clean up open images
	selectImage(nImages);
	close();
}
IJ.log("\\Clear"); // clear Log window
roiManager("reset");
run("Bio-Formats Macro Extensions"); // supports native microscope files


// ---- Open images ----

// open the image file
run("Bio-Formats", "open=&inputImage");

// determine the name of the file without extension

//path = getDirectory("image");
id = getImageID();
imageName = getTitle();
dotIndex = lastIndexOf(imageName, ".");
basename = substring(imageName, 0, dotIndex);

rename("image");

// open the corresponding label image

labelPath = inputLabelDir + File.separator + basename + suffix;
if (File.exists(labelPath)) {
	open(labelPath);
	rename("label");
}
else {
	exit("No matching label image at " + labelPath);
}

// ---- display image nicely ----
selectWindow("label");

// move to trans image
Stack.setPosition(3,11,1);

// adjust contrast and color for trans
Stack.setDisplayMode("color");
Stack.setChannel(3);
run("Grays");
resetMinAndMax;

// adjust contrast and color for Nup159
Stack.setChannel(5);
run("Enhance Contrast", "saturated=0.35");
run("Green");
resetMinAndMax;

// overlay
Property.set("CompositeProjection", "Sum");
Stack.setDisplayMode("composite");
Stack.setActiveChannels("00101");

// ---- Create initial ROIs from the label image ----

selectImage("label");
run("Label Map to ROIs", "connectivity=C4 vertex_location=Corners name_pattern=cell_%03d");

// make sure nothing selected to begin with
//selectImage(id);
//roiManager("Deselect");
//run("Select None");
//
//// check for ROIs
//numROIs = roiManager("count");
//if (numROIs == 0) {
//	showMessage("There are no ROIs saved. Draw ROIs around cells and press T to add each one to the Manager. Then run the macro.");
//	exit;
//}
//// how much to pad ROI numbers?
//digits = Math.ceil((log(numROIs+1)/log(10))); // the +1 is to handle 10 ROIs
//
//setBackgroundColor(0, 0, 0); // set background to black for proper clearing outside 
//
//// ---------- DOCUMENT ROI LOCATIONS
//
//
//// fix colors for Cue5 images
//Stack.setDisplayMode("color");
//Stack.setChannel(3);
//run("Grays");
//resetMinAndMax;
//Stack.setChannel(4);
//run("Red");
//resetMinAndMax;
//Stack.setChannel(5);
//run("Green");
//resetMinAndMax;
//
//if (is("composite")) {
//	Stack.setDisplayMode("composite"); // this command raises error if image is not composite
//	run("Stack to RGB", "keep");
//}
//else {
//	run("Select None");
////	run("Duplicate...", "title=copy duplicate"); // for single-channel non-RGB images; Flatten doesn't create new window
//	run("Duplicate...", "title=copy"); // for single-channel non-RGB images; Flatten doesn't create new window
//}
//rgbID = getImageID();
//selectImage(rgbID);
//
//roiManager("Show All with labels");
////Stack.setPosition(channel, slice, frame); // restore the previous setup
//run("Flatten");
//flatID = getImageID();
//selectImage(flatID);
//saveAs("tiff", imagePath + File.separator + basename + "_ROIlocs.tif");
//
//print("Saved snapshot");
//
//// clean up snapshot images
//if (isOpen(flatID)) {
//	selectImage(flatID);
//	close();
//}
//if (isOpen(rgbID)) {
//	selectImage(rgbID);
//	close();
//}
//	
//// Number and save ROIs
//
//// make sure nothing is selected to begin with
//selectImage(id);
//roiManager("Deselect");
//run("Select None");
//
//for(roiIndex=0; roiIndex < numROIs; roiIndex++) // loop through ROIs
//	{ 
//	selectImage(id);
//	roiNum = roiIndex + 1; // so that image names start with 1 like the ROI labels
//	roiNumPad = IJ.pad(roiNum, digits);
//	cropName = basename + "_roi_"+ roiNumPad + ".tif";
//	roiManager("Select", roiIndex);  // ROI indices start with 0
//	roiManager("Rename", roiNum); // ROI names will start with 1
//	run("Duplicate...", "title=&cropName duplicate"); // creates the cropped stack
//	selectWindow(cropName);
//	
//	// if non-rectangular, clear outside
//	if ((selectionType() != 0) && (selectionType() != -1)) {
//		run("Clear Outside","stack"); // this works because non-rectangular rois are still active on the cropped image
//		run("Select None");// clears the selection that is otherwise saved with the image (although it can be recovered with "restore selection")
//	}
//	
//	saveAs("tiff", imagePath + File.separator + cropName);
//	print("Saved",cropName);
//	close();
//	}	
//	
//// Save ROI set
//run("Select None");
//roiManager("Deselect"); 
//roiSetName = basename + ".zip";
//roiManager("Save", roiPath + File.separator +roiSetName);
//print("Saved ROI set",roiSetName);
//
//// ---------- CLEANUP
//
//run("Select None");
//print("Saved",numROIs,"cropped areas. Finished.");
////close();
